# Generated by Django 2.0.2 on 2019-01-11 22:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acuerdo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('acuerdo', models.TextField()),
                ('num_Voto', models.IntegerField()),
                ('estado', models.CharField(choices=[('Pendiente', 'PENDIENTE'), ('Aceptado', 'ACEPTADO'), ('Rechazado', 'RECHAZADO')], default='Pendiente', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('media', models.FileField(upload_to='')),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('asiste', models.CharField(choices=[('Si', 'SI'), ('No', 'NO')], default='Si', max_length=2)),
                ('justificacion', models.TextField(default='Justificación')),
                ('observacion', models.TextField(default='Observación')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.TextField()),
                ('FK_Acuerdo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acordemos.Acuerdo')),
                ('FK_Asistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acordemos.Asistencia')),
            ],
        ),
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreComision', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('numeroIntegrante', models.IntegerField()),
                ('activa', models.CharField(choices=[('Si', 'SI'), ('No', 'NO')], default='Si', max_length=2)),
                ('quorum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Documento_TipoComision',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoLegal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('referencia', models.CharField(max_length=30)),
                ('enlace', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Enlace',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=300)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Integrante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vota', models.CharField(choices=[('Si', 'SI'), ('No', 'NO')], default='Si', max_length=2)),
                ('fechaInicio', models.DateField()),
                ('fechaTermino', models.DateField()),
                ('FK_Comision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acordemos.Comision')),
            ],
        ),
        migrations.CreateModel(
            name='Invitado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaEnvio', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('fechaReunion', models.DateField()),
                ('horaReunion', models.CharField(max_length=10)),
                ('lugar', models.CharField(max_length=50)),
                ('FK_Comision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acordemos.Comision')),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tema', models.CharField(max_length=40)),
                ('FK_Reunion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acordemos.Reunion')),
            ],
        ),
        migrations.CreateModel(
            name='TipoComision',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreComision', models.CharField(max_length=100)),
                ('quorum', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('numeroIntegrante', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumentoLegal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TipoRol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUnidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.TextField()),
                ('FK_TipoUnidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acordemos.TipoUnidad')),
            ],
        ),
        migrations.CreateModel(
            name='Votacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('voto', models.CharField(choices=[('Aprueba', 'APRUEBA'), ('No Aprueba', 'NOAPRUEBA'), ('Abstiene', 'ABSTIENE')], default='Aprueba', max_length=10)),
                ('FK_Acuerdo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acordemos.Acuerdo')),
                ('FK_Asistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acordemos.Asistencia')),
            ],
        ),
        migrations.AddField(
            model_name='invitado',
            name='FK_Reunion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acordemos.Reunion'),
        ),
        migrations.AddField(
            model_name='integrante',
            name='FK_TipoRol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acordemos.TipoRol'),
        ),
        migrations.AddField(
            model_name='integrante',
            name='FK_User',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enlace',
            name='FK_Tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acordemos.Tema'),
        ),
        migrations.AddField(
            model_name='documentolegal',
            name='FK_TipoDocumentoLegal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acordemos.TipoDocumentoLegal'),
        ),
        migrations.AddField(
            model_name='documento_tipocomision',
            name='FK_DocumentoLegal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acordemos.DocumentoLegal'),
        ),
        migrations.AddField(
            model_name='documento_tipocomision',
            name='TipoComision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acordemos.TipoComision'),
        ),
        migrations.AddField(
            model_name='comision',
            name='FK_DocumentoLegal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acordemos.DocumentoLegal'),
        ),
        migrations.AddField(
            model_name='comision',
            name='FK_Unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acordemos.Unidad'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='FK_Integrante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acordemos.Integrante'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='FK_Reunion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acordemos.Reunion'),
        ),
        migrations.AddField(
            model_name='archivo',
            name='FK_Tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acordemos.Tema'),
        ),
        migrations.AddField(
            model_name='acuerdo',
            name='FK_Tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acordemos.Tema'),
        ),
    ]
