# Generated by Django 2.0.2 on 2019-01-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acordemos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acuerdo',
            name='num_Voto',
            field=models.IntegerField(default=0),
        ),
    ]
