# Generated by Django 2.0.2 on 2019-01-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acordemos', '0002_auto_20190112_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votacion',
            name='voto',
            field=models.CharField(choices=[(1, 'APRUEBA'), (-1, 'NOAPRUEBA'), (0, 'ABSTIENE')], default=1, max_length=10),
        ),
    ]
