# Generated by Django 2.0.2 on 2019-01-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acordemos', '0003_auto_20190112_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votacion',
            name='voto',
            field=models.CharField(choices=[(1, 1), (-1, -1), (0, 0)], default=1, max_length=10),
        ),
    ]
