# Generated by Django 2.0.2 on 2019-01-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acordemos', '0004_auto_20190112_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votacion',
            name='voto',
            field=models.CharField(choices=[('si', 1), (-1, 'no'), (0, 0)], default='si', max_length=10),
        ),
    ]
