# Generated by Django 2.0.2 on 2019-01-12 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Acordemos', '0006_auto_20190112_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acuerdo',
            name='num_Voto',
        ),
    ]
