# Generated by Django 2.0.2 on 2019-01-15 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Acordemos', '0010_acta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acta',
            name='descripcion',
        ),
    ]
